openapi: 3.0.1
info:
  title: PlaceGPT
  description: A collaborative canvas where you can draw anything you want, if you use your words carefully. Users can describe what to add or change on the canvas. If you do not know the user's username, ask them first before making queries to the plugin.
  version: "v1"
servers:
  - url: PLUGIN_HOSTNAME
paths:
  /api/draw:
    post:
      operationId: drawInstruction
      summary: Instruction of what to change on the canvas.
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The name of the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/instructionRequest"
      responses:
        "200":
          description: OK
  /api/stylize:
    post:
      operationId: stylizeImage
      summary: Propmt to styilze a simple image.
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The name of the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/stylizeRequest"
      responses:
        "200":
          description: OK
components:
  schemas:
    instructionRequest:
      type: object
      required:
        - instruction
      properties:
        instruction:
          type: string
          description: A description of what items to add or change on the canvas.
          required: true
    stylizeRequest:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: A stable diffusion prompt to guide the image generation/stylization process.
          required: true
